import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from './ThemeRegistry'
import { SessionProvider } from 'next-auth/react'

import { Container } from '@mui/material'
import AuthProvider from '@/providers/AuthProvider'
import SignInProvider from '@/providers/SignInProvider'
import ReactQueryProvider from '@/providers/ReactQueryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
/*
const AppContainer = styled('div')`
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  background: linear-gradient(#282828, #121212);
  padding: 4rem 1rem 0 1rem;
  min-height: 100vh;
  max-width: 100vw;
  @media (max-width: ${props => props.theme.breakpoints.values.sm}px) {
    padding: 2rem 0.5rem 0 0.5rem;
  }
`*/

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <main>
          <ThemeRegistry options={{ key: 'mui' }}>
            <Container
              sx={{
                background: 'linear-gradient(#282828, #121212)',
                minHeight: '100vh',
                maxWidth: '100vw !important',
                padding: {
                  sm: '2rem 0.5rem 0 0.5rem',
                  md: '4rem 1rem 0 1rem'
                }
              }}
            >
              <AuthProvider>
                <SignInProvider>
                  <ReactQueryProvider>{children}</ReactQueryProvider>
                </SignInProvider>
              </AuthProvider>
            </Container>
          </ThemeRegistry>
        </main>
      </body>
    </html>
  )
}
